### ISSUE TITLE
Broken back button

### ISSUE THREAD

**Issue by jhorwit2** [zhy0216/random-read#4]
If you go to your website & click the Random Walk tab it breaks the back button.

**Comment by zhy0216** [comment]
I am not sure I know what exactly the problem is. Could you provide extra information? or even a screenshot? thx so much

**Comment by peixy0** [comment]
Once you click Random Walk you can't go back to the previous page. Back button takes you to #random-walk which redirects you to another random page.

**Comment by zhy0216** [comment]
yep, it is a bug, i am working on it
