### ISSUE TITLE
You should change your name 

### ISSUE THREAD

**Issue by nicosomb** [zhy0216/random-read#5]
Hello, 

I'm the main developer of @wallabag, ex-poche https://www.wallabag.org/blog/2014/01/24/open-letter-addressed-read-later-inc-creator-pocket
I think it's better for you to change the name of your application ;-) 

Regards, 

Nicolas

**Comment by zhy0216** [comment]
Thanks bro! 
No worries, I do not think `getpocket` will do this because my project is totally opensource and free. More important, I just made it for fun. Their product is for geeks, so they'd better not piss us off :D

**Comment by nicosomb** [comment]
https://lut.im/bCdZv3U5/kv43qKzr
https://lut.im/b0423wme/sWv0q3qq

Good luck.

**Comment by zhy0216** [comment]
thanks again, i will be fine :D
